version: '3'

services:
  django:
    build: .
    container_name: brightmind_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - brightmind_network

volumes:
  static_volume:
  media_volume:

networks:
  brightmind_network:
    driver: bridge
